---
# Install apt-transports package required for Installation of Elasticsearch
- name: install apt-transports
  apt: name=apt-transport-https state=present
#  become: true

# checking if elasticsearch is already installed
- name: Check if elasticsearch is already installed.
  stat: path=/etc/init.d/elasticsearch
  register: elasticsearch_installed

# Adding elastic repo
- apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{ elasticsearch_version }}.x/apt stable main"
    state: present
    filename: 'elastic-{{ elasticsearch_version }}.x'
#  become: true
  when: elasticsearch_installed.stat.exists == false

# updating apt-cache
- name: Update apt cache if repository just added.
  apt: update_cache=yes
  when: elasticsearch_installed.stat.exists == false
#  become: true

# Installing elasticsearch
- name: Install elasticsearch.
  apt: name=elasticsearch state=present force=yes
  notify:
   - restart elasticsearch
#  become: true

# Enable elaticsearch
- name: Enable elasticsearch
  systemd: name=elasticsearch enabled=yes
#  become: true
