---
# tasks file for logstash

- name: Include OS Specific setup tasks
  include_tasks: prerequisite.yml

- name: Include OS Specific setup tasks
  include_tasks: es-{{ ansible_os_family }}.yml

- name: Configuring elasticsearch
  include_tasks: config.yml
