---
# install libselinux-python on centos7
- name: Install net-tools
  yum: name=net-tools
  when:
    - "ansible_os_family == 'RedHat'"

- name: Set vm.swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ swapness }}"
    state: present

- name: Set virtual max area
  sysctl:
    name: vm.max_map_count
    value: "{{ vm_max_count }}"
    state: present
