---
# handlers file for elasticsearch
- name: restart elasticsearch
  service:
    name: elasticsearch
    state: restarted
    enabled: true

# reload systemd after modification
- name: reload systemd
  systemd:
    daemon_reload: true
